spring.application.name=cryptoCentinela
# Activa la consola web de H2
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Define una URL fija para que sea facil entrar (si no, cambia cada vez)
spring.datasource.url=jdbc:h2:file:./data/sentineldb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Esto permite que la consola se vea bien en navegadores modernos
spring.h2.console.settings.web-allow-others=true

# Lista de IDs oficiales de CoinGecko (separados por coma)
sentinel.crypto.ids=bitcoin,ethereum,chainlink,aave,polkadot,solana

# Umbral de caida (0.10 es 10%)
sentinel.alert.threshold=-0.05

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.chat.id=${TELEGRAM_CHAT_ID}